### ISSUE TITLE
Webapp no longer online

### ISSUE THREAD

**Issue by 0xjmux** [gbmhunter/NinjaCalc#237]
Hi,
I was trying to access the web app today and It seems like it's offline. Can you check and see if you can bring it back up? Thanks!

[ninja-calc.mbedded.ninja/](http://ninja-calc.mbedded.ninja/)

![image](https://github.com/gbmhunter/NinjaCalc/assets/20913473/8131bdf0-9237-4e12-8d73-622cee0f9fe2)

**Comment by gbmhunter** [comment]
Hi @0xjmux ! Thanks for the report. I changed the URL from ninja-calc.mbedded.ninja to ninjacalc.mbedded.ninja so it better matched the syntax of my other two tools (ninjaterm.mbedded.ninja and blog.mbedded.ninja). I had forgot to update the link on the NinjaCalc homepage though! I've fixed that now.
